#! /bin/bash

if ! (return 0 2>/dev/null) 
then
    echo This script cannot be executed directly and should be sourced. E.g.: 
    echo source "${BASH_SOURCE[0]}"
    exit 1
fi

export SHARED_DIR=$(pwd)
export HOST_MACHINE=$(hostname)

SCRIPT_DIR=$( cd -- "$( dirname -- $(realpath "${BASH_SOURCE[0]}") )" &> /dev/null && pwd )
export ENVIRONMENT="${SCRIPT_DIR}/taskvine-env"


source $(realpath "${ENVIRONMENT}/bin/activate")

echo "Environment taskvine-env activated."
